### ISSUE TITLE
DSL incompatibility

### ISSUE THREAD

**Issue by mrseeyon** [metagenlab/zDB#117] opened 2024-07-16 18:32 UTC
When I am trying to run the zdb, if gives me the following error: 
 
zdb run --input=input.csv --name=simple_run --resume                
 
 N E X T F L O W   ~  version 24.04.3
WARN: It appears you have never run this project before -- Option `-resume` is ignored
Nextflow DSL1 is no longer supported — Update your script to DSL2, or use Nextflow 22.10.x or earlier.

I am using MacOS, python version 3.12.4 (using miniconda environment)

**Comment by njohner** [comment] 2024-07-19 10:20
How did you install zDB? via bioconda? The 1.3 release on bioconda is currently broken, I need to make a new release and get it merged. Will do that today.

**Comment by njohner** [comment] 2024-07-19 15:46
Ok if you installed over bioconda, try updating or installing again. Version 1.3.1 is out and should work.

**Comment by mwittep** [comment] 2024-08-06 09:20
The mamba/conda installer still automatically installs version 24, which is not compatible with the old DSL1. 

For it to work, you can simply set the environmental variable `NXF_VER=22.10.0`.

**Comment by njohner** [comment] 2024-08-07 15:17
zDB is no longer DSL1, so installing version 24 of nextflow is fine. What version of zDB are you running (type `zdb` and it should tell you the version right at the top of the output)?
Try creating a fresh environment with `mamba create --name zdb -c conda-forge -c bioconda zdb singularity` which should install the latest zdb version, or you can force the latest version with `mamba create --name zdb -c conda-forge -c bioconda zdb=1.3.2 singularity`

**Comment by mwittep** [comment] 2024-08-07 17:34
Not sure why, but mamba installed version 1.2.1. I will need to check why it did not install the correct version, since I ended up using the source compiled version. 

But thanks for the response!

**Comment by njohner** [comment] 2024-08-08 13:37
From what I've seen, the issue is that starting from zDB v1.2.1 build 1, there is a dependency on mamba which is not part of bioconda. So you need to add the conda-forge channel in order to get a newer version of zDB.

**Closed** 2024-08-08 13:42 UTC
